# Pandas Notes - FCSP-2 Unit 1

## What is Pandas?
Pandas is a Python library for working with structured/tabular data (like Excel in Python).
```python
import pandas as pd  # Always import at the start
```
---
## Concept 1: Series
A **Series** is a single column of data with labels (index).

### Syntax:
```python
pd.Series(data, index=[...])
```
### Key Points:
- Like a single Excel column with row labels
- Index is optional (defaults to 0, 1, 2...)
- All values are of the same data type

In [25]:
import pandas as pd

In [26]:
marks = pd.Series([24,23,19,20],index=['DM','FSD','COA','TOC'])
print(marks)

DM     24
FSD    23
COA    19
TOC    20
dtype: int64

In [27]:
#Task-1:
prices = pd.Series([600000,750000,900000],index = ['Swift','Baleno','Nexon'])
print(prices)

Swift     600000
Baleno    750000
Nexon     900000
dtype: int64

## Concept 2: DataFrame
A DataFrame is a 2D table with rows and columns — the core structure in Pandas.
Each column in a DataFrame is a Series.

### Creating a DataFrame from a dictionary:
```python
import pandas as pd

data = {
    "Name":  ["Alice", "Bob", "Charlie"],
    "Marks": [85, 90, 78],
    "Grade": ["A", "A+", "B"]
}

df = pd.DataFrame(data)
print(df)
```

### Key Points:
- Dictionary keys become column names
- Row labels (index) are auto-assigned as 0, 1, 2...
- Each column is internally a Series
- `df` is the standard variable name convention for a DataFrame

In [28]:
data = {
  'Name':['Alice','Bob','Charlie'],
  'Marks':[85,90,70],
  'Grade':['A-','A','C']
}

df = pd.DataFrame(data)
print(df)

      Name  Marks Grade
0    Alice     85    A-
1      Bob     90     A
2  Charlie     70     C

In [29]:
#Task-2:
data ={
  'Car':['Swift','Nexon','City'],
  'Fuel':['Petrol','Diesel','Petrol'],
  'Price':[600000,900000,1100000]
  }

cars = pd.DataFrame(data)
print(cars)

     Car    Fuel    Price
0  Swift  Petrol   600000
1  Nexon  Diesel   900000
2   City  Petrol  1100000

## Concept 3: Reading CSV & Exploring Data

### Loading a CSV file:
```python
df = pd.read_csv("filename.csv")
```

### Exploration functions to run immediately after loading:
```python
df.head()      # First 5 rows
df.head(10)    # First n rows
df.tail()      # Last 5 rows
df.shape       # (rows, columns) — property, no brackets
df.info()      # Column names, data types, missing value counts
df.describe()  # Statistical summary of numeric columns
```

### What info() tells you:
- Which columns have missing values
- Data type of each column (int, float, object)
- Memory usage of the DataFrame

### Professional Habit:
Always run head(), info(), and describe() immediately after
loading any new dataset. This is called a "first look" and is
standard practice in every data science workflow.

In [30]:
stock_data = pd.read_csv('/home/shlok/College/SemIV/FCSP2/01-pandas-eda/532540.csv')
stock_data.head()

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open
0,27-February-2026,2678.00,2688.20,2627.00,2636.40,2650.054612,139073,11196,3.685510e+08,72402,52.06,61.20,-41.60
1,26-February-2026,2636.20,2670.00,2634.80,2647.70,2651.099860,180513,25439,4.785580e+08,82614,45.77,35.20,11.50
2,25-February-2026,2580.55,2653.45,2580.55,2629.50,2632.554614,275224,26142,7.245422e+08,128893,46.83,72.90,48.95
3,24-February-2026,2640.00,2648.70,2561.95,2574.50,2591.166532,403845,29163,1.046430e+09,277152,68.63,86.75,-65.50
4,23-February-2026,2686.65,2704.45,2660.45,2675.85,2677.955705,209954,18874,5.622475e+08,116292,55.39,44.00,-10.80

In [31]:
stock_data.head(10)

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open
0,27-February-2026,2678.00,2688.20,2627.00,2636.40,2650.054612,139073,11196,3.685510e+08,72402,52.06,61.20,-41.60
1,26-February-2026,2636.20,2670.00,2634.80,2647.70,2651.099860,180513,25439,4.785580e+08,82614,45.77,35.20,11.50
2,25-February-2026,2580.55,2653.45,2580.55,2629.50,2632.554614,275224,26142,7.245422e+08,128893,46.83,72.90,48.95
3,24-February-2026,2640.00,2648.70,2561.95,2574.50,2591.166532,403845,29163,1.046430e+09,277152,68.63,86.75,-65.50
4,23-February-2026,2686.65,2704.45,2660.45,2675.85,2677.955705,209954,18874,5.622475e+08,116292,55.39,44.00,-10.80
5,20-February-2026,2676.95,2702.85,2648.45,2686.65,2684.080134,180374,13118,4.841383e+08,89054,49.37,54.40,9.70
6,19-February-2026,2716.25,2748.00,2668.00,2680.45,2706.301442,181680,20392,4.916808e+08,56116,30.89,80.00,-35.80
7,18-February-2026,2735.75,2735.75,2658.00,2694.60,2687.164825,211740,25687,5.689803e+08,107852,50.94,77.75,-41.15
8,17-February-2026,2715.00,2759.30,2695.05,2717.45,2736.633202,343290,20437,9.394588e+08,141022,41.08,64.25,2.45
9,16-February-2026,2700.00,2720.00,2671.50,2708.20,2690.860418,377663,13097,1.016238e+09,240718,63.74,48.50,8.20

In [32]:
stock_data.tail()

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open
242,7-March-2025,3624.95,3624.95,3575.00,3611.30,3600.962211,30644,3720,110347886.0,11253,36.72,49.95,-13.65
243,6-March-2025,3568.00,3608.95,3536.15,3599.70,3568.352705,52086,6991,185861219.0,17565,33.72,72.80,31.70
244,5-March-2025,3529.95,3598.00,3521.10,3549.35,3568.937330,50343,6537,179671012.0,19151,38.04,76.90,19.40
245,4-March-2025,3483.95,3549.90,3463.80,3532.65,3515.291581,68643,9179,241300160.0,22497,32.77,86.10,48.70
246,3-March-2025,3499.85,3523.95,3475.00,3496.55,3498.257060,90088,10802,315150982.0,37769,41.92,48.95,-3.30

In [33]:
stock_data.shape

(247, 13)

In [34]:
stock_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       247 non-null    object
 1   Open Price                 247 non-null    float64
 2   High Price                 247 non-null    float64
 3   Low Price                  247 non-null    float64
 4   Close Price                247 non-null    float64
 5   WAP                        247 non-null    float64
 6   No.of Shares               247 non-null    int64
 7   No. of Trades              247 non-null    int64
 8   Total Turnover (Rs.)       247 non-null    float64
 9   Deliverable Quantity       247 non-null    int64
 10  % Deli. Qty to Traded Qty  247 non-null    float64
 11  Spread High-Low            247 non-null    float64
 12  Spread Close-Open          247 non-null    float64
dtypes: float64(9), int64(3), object(1)
memory usage: 25.2+ KB

In [35]:
stock_data.describe()

,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open
count,247.000000,247.000000,247.000000,247.000000,247.000000,2.470000e+02,247.000000,2.470000e+02,247.000000,247.000000,247.000000,247.000000
mean,3218.823684,3244.112551,3188.804049,3215.179150,3215.300908,1.889784e+05,13908.821862,5.960432e+08,88794.238866,49.653765,55.308502,-3.644534
std,226.141470,227.365536,225.041467,227.697841,226.725583,1.785009e+05,10607.884227,5.518822e+08,103863.277122,18.235857,27.713223,40.108005
min,2579.000000,2648.700000,2561.950000,2574.500000,2591.166532,1.854100e+04,2090.000000,6.344654e+07,7969.000000,5.870000,14.900000,-131.650000
25%,3060.125000,3085.475000,3039.800000,3057.575000,3058.714481,7.447050e+04,6693.000000,2.414537e+08,36043.000000,38.870000,36.375000,-26.075000
50%,3198.700000,3221.050000,3161.000000,3191.600000,3190.084437,1.354700e+05,10614.000000,4.258445e+08,61687.000000,50.930000,48.950000,-5.600000
75%,3423.800000,3447.750000,3397.125000,3423.525000,3421.611189,2.201020e+05,17436.500000,7.113001e+08,104048.000000,63.790000,68.775000,18.375000
max,3661.000000,3708.900000,3638.050000,3657.700000,3673.370650,1.303141e+06,57005.000000,4.011928e+09,897147.000000,91.690000,229.750000,216.350000

## Concept 4: Cleaning Data

### 4.1 Checking and Handling Missing Values:
```python
df.isnull()                          # True/False for every cell
df.isnull().sum()                    # Missing value count per column
df.dropna()                          # Drop rows with any missing value
df.dropna(subset=["ColumnName"])     # Drop rows where specific column is missing
df.fillna(0)                         # Fill missing with 0
df.fillna(df.mean(numeric_only=True)) # Fill missing with column mean
```

### 4.2 Handling Duplicates:
```python
df.duplicated().sum()   # Count duplicate rows
df.drop_duplicates()    # Remove duplicate rows
```

### 4.3 Dropping Columns or Rows:
```python
df = df.drop(columns=["ColumnName"])  # Drop a column
df = df.drop(index=2)                 # Drop a row by index number
```

### Key Notes:
- Always check isnull().sum() before any analysis
- inplace=True modifies original — reassigning (df = df.drop(...))
  is safer and more readable
- Date columns loaded as object type need pd.to_datetime() conversion

In [36]:
#Task-3:
print("Missing Values in each Col:",stock_data.isnull().sum())
print("Duplicate Rows:",stock_data.duplicated().sum())
stock_data.drop(columns = ['WAP'],inplace=True)
print(stock_data.info())

Missing Values in each Col: Date                         0
Open Price                   0
High Price                   0
Low Price                    0
Close Price                  0
WAP                          0
No.of Shares                 0
No. of Trades                0
Total Turnover (Rs.)         0
Deliverable Quantity         0
% Deli. Qty to Traded Qty    0
Spread High-Low              0
Spread Close-Open            0
dtype: int64
Duplicate Rows: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       247 non-null    object
 1   Open Price                 247 non-null    float64
 2   High Price                 247 non-null    float64
 3   Low Price                  247 non-null    float64
 4   Close Price                247 non-null    float64
 5   No.of Shares               247 non-null    int64
 6   No. of Trades              247 non-null    int64
 7   Total Turnover (Rs.)       247 non-null    float64
 8   Deliverable Quantity       247 non-null    int64
 9   % Deli. Qty to Traded Qty  247 non-null    float64
 10  Spread High-Low            247 non-null    float64
 11  Spread Close-Open          247 non-null    float64
dtypes: float64(8), int64(3), object(1)
memory usage: 23.3+ KB
None

## Concept 5: Selecting Data with loc[] and iloc[]

### loc[] — Select by Label:
```python
df.loc[0]                        # Single row
df.loc[0:3]                      # Range of rows
df.loc[0:3, ["Col1", "Col2"]]    # Rows and specific columns
df.loc[df["Column"] > value]     # Rows matching a condition
df.loc[
    (df["Col1"] > val1) & 
    (df["Col2"] < val2)
]                                # Multiple conditions
```

### iloc[] — Select by Position:
```python
df.iloc[0]           # First row
df.iloc[0:5]         # First 5 rows
df.iloc[0:5, 0:3]    # First 5 rows, first 3 columns
```

### Key Difference:
- loc[]  → uses labels (column names, index labels)
- iloc[] → uses integer positions (0, 1, 2...)

### Professional Habit:
Always use loc[] over plain indexing (df[0:3]).
It is explicit, readable, and unambiguous.

In [42]:
print('Single Row:',stock_data.loc[0])

print('Multiple Rows:',stock_data.loc[0:3])

print("Specific Rows and Columns:",stock_data.loc[0:3, ["Date", "Close Price"]])

print("Rows Satisfying the Condition:",stock_data.loc[stock_data["Close Price"] > 2700])

print('Rows Satisfying Multiple Condition:',stock_data.loc[(stock_data["Close Price"] > 2700) & (stock_data["No.of Shares"] > 200000)])

Single Row: Date                         27-February-2026
Open Price                             2678.0
High Price                             2688.2
Low Price                              2627.0
Close Price                            2636.4
No.of Shares                           139073
No. of Trades                           11196
Total Turnover (Rs.)              368551045.0
Deliverable Quantity                    72402
% Deli. Qty to Traded Qty               52.06
Spread High-Low                          61.2
Spread Close-Open                       -41.6
Name: 0, dtype: object
Multiple Rows:                Date  Open Price  High Price  Low Price  Close Price  \
0  27-February-2026     2678.00     2688.20    2627.00       2636.4
1  26-February-2026     2636.20     2670.00    2634.80       2647.7
2  25-February-2026     2580.55     2653.45    2580.55       2629.5
3  24-February-2026     2640.00     2648.70    2561.95       2574.5

   No.of Shares  No. of Trades  Total Turnover (Rs.)  Deliverable Quantity  \
0        139073          11196          3.685510e+08                 72402
1        180513          25439          4.785580e+08                 82614
2        275224          26142          7.245422e+08                128893
3        403845          29163          1.046430e+09                277152

   % Deli. Qty to Traded Qty  Spread High-Low  Spread Close-Open
0                      52.06            61.20             -41.60
1                      45.77            35.20              11.50
2                      46.83            72.90              48.95
3                      68.63            86.75             -65.50
Specific Rows and Columns:                Date  Close Price
0  27-February-2026       2636.4
1  26-February-2026       2647.7
2  25-February-2026       2629.5
3  24-February-2026       2574.5
Rows Satisfying the Condition:                  Date  Open Price  High Price  Low Price  Close Price  \
8    17-February-2026     2715.00     2759.30    2695.05      2717.45
9    16-February-2026     2700.00     2720.00    2671.50      2708.20
11   12-February-2026     2883.55     2883.55    2740.15      2751.90
12   11-February-2026     2984.65     2998.00    2905.00      2909.40
13   10-February-2026     2950.00     3011.00    2943.55      2984.25
..                ...         ...         ...        ...          ...
242      7-March-2025     3624.95     3624.95    3575.00      3611.30
243      6-March-2025     3568.00     3608.95    3536.15      3599.70
244      5-March-2025     3529.95     3598.00    3521.10      3549.35
245      4-March-2025     3483.95     3549.90    3463.80      3532.65
246      3-March-2025     3499.85     3523.95    3475.00      3496.55

     No.of Shares  No. of Trades  Total Turnover (Rs.)  Deliverable Quantity  \
8          343290          20437          9.394588e+08                141022
9          377663          13097          1.016238e+09                240718
11         715354          54483          1.990066e+09                377778
12         149418          15949          4.398339e+08                 93281
13         468333           9320          1.395098e+09                400021
..            ...            ...                   ...                   ...
242         30644           3720          1.103479e+08                 11253
243         52086           6991          1.858612e+08                 17565
244         50343           6537          1.796710e+08                 19151
245         68643           9179          2.413002e+08                 22497
246         90088          10802          3.151510e+08                 37769

     % Deli. Qty to Traded Qty  Spread High-Low  Spread Close-Open
8                        41.08            64.25               2.45
9                        63.74            48.50               8.20
11                       52.81           143.40            -131.65
12                       62.43            93.00             -75.25
13                       85.41            67.45              34.25
..                         ...              ...                ...
242                      36.72            49.95             -13.65
243                      33.72            72.80              31.70
244                      38.04            76.90              19.40
245                      32.77            86.10              48.70
246                      41.92            48.95              -3.30

[238 rows x 12 columns]
Rows Satisfying Multiple Condition:                  Date  Open Price  High Price  Low Price  Close Price  \
8    17-February-2026     2715.00     2759.30    2695.05      2717.45
9    16-February-2026     2700.00     2720.00    2671.50      2708.20
11   12-February-2026     2883.55     2883.55    2740.15      2751.90
13   10-February-2026     2950.00     3011.00    2943.55      2984.25
15    6-February-2026     2992.00     2992.00    2915.15      2941.45
..                ...         ...         ...        ...          ...
198       16-May-2025     3580.95     3586.00    3547.00      3562.95
220     11-April-2025     3290.00     3298.40    3205.25      3232.30
222      8-April-2025     3299.00     3348.90    3255.30      3293.55
223      7-April-2025     3060.25     3290.00    3060.25      3276.60
225      3-April-2025     3485.40     3498.00    3396.10      3403.90

     No.of Shares  No. of Trades  Total Turnover (Rs.)  Deliverable Quantity  \
8          343290          20437          9.394588e+08                141022
9          377663          13097          1.016238e+09                240718
11         715354          54483          1.990066e+09                377778
13         468333           9320          1.395098e+09                400021
15         388720          26462          1.139534e+09                259026
..            ...            ...                   ...                   ...
198        239863          11580          8.533575e+08                149512
220        229229          16912          7.436517e+08                137786
222        263659          21906          8.684424e+08                133078
223        274432          31158          8.681449e+08                134454
225        207922          25985          7.131182e+08                135458

     % Deli. Qty to Traded Qty  Spread High-Low  Spread Close-Open
8                        41.08            64.25               2.45
9                        63.74            48.50               8.20
11                       52.81           143.40            -131.65
13                       85.41            67.45              34.25
15                       66.64            76.85             -50.55
..                         ...              ...                ...
198                      62.33            39.00             -18.00
220                      60.11            93.15             -57.70
222                      50.47            93.60              -5.45
223                      48.99           229.75             216.35
225                      65.15           101.90             -81.50

[65 rows x 12 columns]

In [44]:
#Task-4:
print("Display rows 10 to 20, showing only Date and Close Price:",
stock_data.loc[10:20 , ['Date','Close Price']])
print("Display all rows where Close Price is greater than 2700",
stock_data.loc[stock_data["Close Price"] > 2700])
print("Display rows where Close Price is greater than 2700 AND No.of Shares is greater than 300000",stock_data.loc[(stock_data["Close Price"] > 2700) & (stock_data["No.of Shares"] > 300000)])

Display rows 10 to 20, showing only Date and Close Price:                 Date  Close Price
10  13-February-2026      2692.15
11  12-February-2026      2751.90
12  11-February-2026      2909.40
13  10-February-2026      2984.25
14   9-February-2026      2947.10
15   6-February-2026      2941.45
16   5-February-2026      2992.05
17   4-February-2026      2999.80
18   3-February-2026      3223.70
19   2-February-2026      3169.30
20   1-February-2026      3185.15
Display all rows where Close Price is greater than 2700                  Date  Open Price  High Price  Low Price  Close Price  \
8    17-February-2026     2715.00     2759.30    2695.05      2717.45
9    16-February-2026     2700.00     2720.00    2671.50      2708.20
11   12-February-2026     2883.55     2883.55    2740.15      2751.90
12   11-February-2026     2984.65     2998.00    2905.00      2909.40
13   10-February-2026     2950.00     3011.00    2943.55      2984.25
..                ...         ...         ...        ...          ...
242      7-March-2025     3624.95     3624.95    3575.00      3611.30
243      6-March-2025     3568.00     3608.95    3536.15      3599.70
244      5-March-2025     3529.95     3598.00    3521.10      3549.35
245      4-March-2025     3483.95     3549.90    3463.80      3532.65
246      3-March-2025     3499.85     3523.95    3475.00      3496.55

     No.of Shares  No. of Trades  Total Turnover (Rs.)  Deliverable Quantity  \
8          343290          20437          9.394588e+08                141022
9          377663          13097          1.016238e+09                240718
11         715354          54483          1.990066e+09                377778
12         149418          15949          4.398339e+08                 93281
13         468333           9320          1.395098e+09                400021
..            ...            ...                   ...                   ...
242         30644           3720          1.103479e+08                 11253
243         52086           6991          1.858612e+08                 17565
244         50343           6537          1.796710e+08                 19151
245         68643           9179          2.413002e+08                 22497
246         90088          10802          3.151510e+08                 37769

     % Deli. Qty to Traded Qty  Spread High-Low  Spread Close-Open
8                        41.08            64.25               2.45
9                        63.74            48.50               8.20
11                       52.81           143.40            -131.65
12                       62.43            93.00             -75.25
13                       85.41            67.45              34.25
..                         ...              ...                ...
242                      36.72            49.95             -13.65
243                      33.72            72.80              31.70
244                      38.04            76.90              19.40
245                      32.77            86.10              48.70
246                      41.92            48.95              -3.30

[238 rows x 12 columns]
Display rows where Close Price is greater than 2700 AND No.of Shares is greater than 300000                   Date  Open Price  High Price  Low Price  Close Price  \
8     17-February-2026     2715.00     2759.30    2695.05      2717.45
9     16-February-2026     2700.00     2720.00    2671.50      2708.20
11    12-February-2026     2883.55     2883.55    2740.15      2751.90
13    10-February-2026     2950.00     3011.00    2943.55      2984.25
15     6-February-2026     2992.00     2992.00    2915.15      2941.45
16     5-February-2026     2998.95     3029.50    2970.35      2992.05
17     4-February-2026     3122.00     3122.00    2986.85      2999.80
28     20-January-2026     3152.00     3160.90    3094.05      3108.05
31     14-January-2026     3264.95     3264.95    3183.05      3192.30
35      8-January-2026     3294.45     3294.45    3181.60      3204.30
49    18-December-2025     3234.70     3288.70    3224.05      3280.10
54    11-December-2025     3206.00     3207.75    3153.75      3191.60
58     5-December-2025     3239.50     3270.70    3223.25      3238.90
59     4-December-2025     3181.25     3249.95    3181.25      3228.90
64    27-November-2025     3174.15     3178.85    3125.00      3136.90
69    20-November-2025     3150.00     3163.50    3137.15      3145.75
74    13-November-2025     3131.25     3132.00    3101.05      3105.70
75    12-November-2025     3056.10     3136.00    3056.10      3131.25
79     6-November-2025     2989.80     3024.00    2989.80      3011.05
88     23-October-2025     3040.00     3097.95    3038.60      3074.65
90     20-October-2025     2971.15     3022.00    2971.15      3014.25
92     16-October-2025     2969.00     2974.55    2944.25      2970.85
97      9-October-2025     3035.00     3066.55    3020.15      3061.95
98      8-October-2025     2973.85     3042.00    2969.00      3026.85
102     1-October-2025     2889.00     2924.40    2867.55      2914.10
105  26-September-2025     2940.00     2952.00    2892.00      2900.10
106  25-September-2025     3024.95     3030.35    2951.00      2960.35
109  22-September-2025     3070.10     3106.60    3063.05      3074.05
111  18-September-2025     3186.80     3202.95    3161.00      3176.25
116  11-September-2025     3133.05     3138.30    3110.15      3123.95
121   4-September-2025     3120.00     3120.00    3090.10      3095.75
127     26-August-2025     3130.00     3163.40    3121.00      3156.25
158       11-July-2025     3314.00     3337.25    3261.35      3265.40
161        8-July-2025     3410.00     3424.00    3394.05      3406.35
171       24-June-2025     3430.50     3442.80    3382.40      3390.20
173       20-June-2025     3424.35     3445.60    3408.50      3434.35
176       17-June-2025     3510.00     3522.30    3488.20      3515.25
181       10-June-2025     3440.00     3485.00    3424.00      3463.50
186        3-June-2025     3449.95     3472.45    3399.40      3405.05
191        27-May-2025     3537.35     3538.80    3481.85      3498.90

     No.of Shares  No. of Trades  Total Turnover (Rs.)  Deliverable Quantity  \
8          343290          20437          9.394588e+08                141022
9          377663          13097          1.016238e+09                240718
11         715354          54483          1.990066e+09                377778
13         468333           9320          1.395098e+09                400021
15         388720          26462          1.139534e+09                259026
16         387547          42367          1.161430e+09                158432
17         962707          46113          2.906506e+09                804058
28         588857           6293          1.832339e+09                539943
31         428686          31547          1.375189e+09                206868
35         446517          36938          1.433855e+09                153288
49         309024          30156          1.009854e+09                 41640
54         397514          23648          1.266559e+09                 39307
58         350070          15947          1.137296e+09                223499
59         532289          25418          1.718688e+09                141420
64         401820          28530          1.261514e+09                 48610
69         361891          21681          1.139412e+09                 61965
74         477009          28641          1.483329e+09                109178
75         309022          22297          9.601755e+08                210479
79         586552          23982          1.766267e+09                135051
88        1303141          36251          4.011928e+09                897147
90         492693          14335          1.478712e+09                429587
92         534755          28779          1.586441e+09                110584
97         439505          19350          1.342689e+09                 88076
98         360325          22078          1.090020e+09                204436
102        566102          27231          1.644466e+09                140091
105        590085          52763          1.721609e+09                446668
106        569581          57005          1.695550e+09                231307
109        385138          44969          1.187667e+09                217436
111        365538          28675          1.162135e+09                 63476
116        533044          38168          1.663813e+09                 74157
121        394965          29218          1.223883e+09                 38789
127        609827          37522          1.921946e+09                107693
158        453988          45736          1.492431e+09                312042
161        377142          15549          1.284724e+09                 48608
171        771522          25978          2.622190e+09                 71077
173        419497           9896          1.434371e+09                316711
176        570631          18378          2.005421e+09                 33503
181        313572          20198          1.085917e+09                 62698
186        919365          54188          3.140541e+09                 94439
191        545274          34275          1.909114e+09                 79095

     % Deli. Qty to Traded Qty  Spread High-Low  Spread Close-Open
8                        41.08            64.25               2.45
9                        63.74            48.50               8.20
11                       52.81           143.40            -131.65
13                       85.41            67.45              34.25
15                       66.64            76.85             -50.55
16                       40.88            59.15              -6.90
17                       83.52           135.15            -122.20
28                       91.69            66.85             -43.95
31                       48.26            81.90             -72.65
35                       34.33           112.85             -90.15
49                       13.47            64.65              45.40
54                        9.89            54.00             -14.40
58                       63.84            47.45              -0.60
59                       26.57            68.70              47.65
64                       12.10            53.85             -37.25
69                       17.12            26.35              -4.25
74                       22.89            30.95             -25.55
75                       68.11            79.90              75.15
79                       23.02            34.20              21.25
88                       68.84            59.35              34.65
90                       87.19            50.85              43.10
92                       20.68            30.30               1.85
97                       20.04            46.40              26.95
98                       56.74            73.00              53.00
102                      24.75            56.85              25.10
105                      75.70            60.00             -39.90
106                      40.61            79.35             -64.60
109                      56.46            43.55               3.95
111                      17.36            41.95             -10.55
116                      13.91            28.15              -9.10
121                       9.82            29.90             -24.25
127                      17.66            42.40              26.25
158                      68.73            75.90             -48.60
161                      12.89            29.95              -3.65
171                       9.21            60.40             -40.30
173                      75.50            37.10              10.00
176                       5.87            34.10               5.25
181                      19.99            61.00              23.50
186                      10.27            73.05             -44.90
191                      14.51            56.95             -38.45